create extension if not exists pgcrypto;

create table if not exists public.cases (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  client_name text,
  contract_text text not null,
  synthetic boolean not null default false,
  environment text not null default 'production' check (environment in ('production','test')),
  external_test_id text unique,
  status text not null default 'pendente' check (status in ('pendente','em-analise','aguardando-revisao','requer-correcao','concluido','erro')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.analyses (
  id uuid primary key default gen_random_uuid(),
  case_id uuid not null references public.cases(id) on delete cascade,
  analyst_json jsonb not null,
  audit_json jsonb not null,
  final_classification text not null,
  auditor_recommendation text not null,
  quality_gate boolean not null default false,
  validation_errors jsonb not null default '[]'::jsonb,
  legal_source_version text,
  memorandum_version text,
  model_name text,
  created_at timestamptz not null default now()
);

create table if not exists public.reviews (
  id uuid primary key default gen_random_uuid(),
  case_id uuid not null references public.cases(id) on delete cascade,
  analysis_id uuid not null references public.analyses(id) on delete cascade,
  reviewer_name text not null,
  reviewer_oab text,
  decision text not null check (decision in ('aprovado','devolver')),
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  case_id uuid references public.cases(id) on delete cascade,
  analysis_id uuid references public.analyses(id) on delete cascade,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_cases_synthetic on public.cases(synthetic);
create index if not exists idx_cases_environment on public.cases(environment);
create index if not exists idx_analyses_case_id on public.analyses(case_id);
create index if not exists idx_reviews_case_id on public.reviews(case_id);
create index if not exists idx_audit_logs_case_id on public.audit_logs(case_id);

alter table public.cases enable row level security;
alter table public.analyses enable row level security;
alter table public.reviews enable row level security;
alter table public.audit_logs enable row level security;

-- Sem policies públicas: o navegador NÃO acessa as tabelas diretamente.
-- O backend usa SUPABASE_SERVICE_ROLE_KEY, guardada apenas no ambiente do servidor.

-- v3.9 multiusuário
alter table public.cases add column if not exists owner_id uuid references auth.users(id) on delete set null;
alter table public.reviews add column if not exists reviewer_user_id uuid references auth.users(id) on delete set null;
alter table public.audit_logs add column if not exists actor_user_id uuid references auth.users(id) on delete set null;
create table if not exists public.user_settings (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  oab_number text,
  default_theme text not null default 'light' check (default_theme in ('light','dark')),
  compact_mode boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.user_settings enable row level security;
create index if not exists idx_cases_owner_id on public.cases(owner_id);
