create extension if not exists pgcrypto;

create table if not exists public.cases (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  client_name text,
  contract_text text not null,
  status text not null default 'pendente' check (status in ('pendente','em-analise','aguardando-revisao','requer-correcao','concluido','erro')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.analyses (
  id uuid primary key default gen_random_uuid(),
  case_id uuid not null references public.cases(id) on delete cascade,
  analyst_json jsonb not null,
  audit_json jsonb not null,
  final_classification text not null,
  auditor_recommendation text not null,
  quality_gate boolean not null default false,
  validation_errors jsonb not null default '[]'::jsonb,
  legal_source_version text,
  memorandum_version text,
  model_name text,
  created_at timestamptz not null default now()
);

create table if not exists public.reviews (
  id uuid primary key default gen_random_uuid(),
  case_id uuid not null references public.cases(id) on delete cascade,
  analysis_id uuid not null references public.analyses(id) on delete cascade,
  reviewer_name text not null,
  reviewer_oab text,
  decision text not null check (decision in ('aprovado','devolver')),
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  case_id uuid references public.cases(id) on delete cascade,
  analysis_id uuid references public.analyses(id) on delete cascade,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_analyses_case_id on public.analyses(case_id);
create index if not exists idx_reviews_case_id on public.reviews(case_id);
create index if not exists idx_audit_logs_case_id on public.audit_logs(case_id);

alter table public.cases enable row level security;
alter table public.analyses enable row level security;
alter table public.reviews enable row level security;
alter table public.audit_logs enable row level security;

-- MVP / teste com publishable key.
-- O acesso do usuário final continua passando pelo backend do app, mas estas policies
-- também tornam as tabelas acessíveis a qualquer cliente que possua a publishable key.
-- NÃO use esta configuração para contratos reais/confidenciais.

drop policy if exists "mvp_anon_cases_all" on public.cases;
create policy "mvp_anon_cases_all" on public.cases for all to anon using (true) with check (true);

drop policy if exists "mvp_anon_analyses_all" on public.analyses;
create policy "mvp_anon_analyses_all" on public.analyses for all to anon using (true) with check (true);

drop policy if exists "mvp_anon_reviews_all" on public.reviews;
create policy "mvp_anon_reviews_all" on public.reviews for all to anon using (true) with check (true);

drop policy if exists "mvp_anon_audit_logs_all" on public.audit_logs;
create policy "mvp_anon_audit_logs_all" on public.audit_logs for all to anon using (true) with check (true);
