import assert from 'node:assert/strict';
import fs from 'node:fs';
const api=fs.readFileSync(new URL('../api/index.js',import.meta.url),'utf8');
const app=fs.readFileSync(new URL('../app.js',import.meta.url),'utf8');
const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
const actionAuth=fs.readFileSync(new URL('../lib/actionAuth.js',import.meta.url),'utf8');
const migration=fs.readFileSync(new URL('../supabase/migration_v3_10_auth_billing.sql',import.meta.url),'utf8');
assert.match(api,/APP_VERSION = '3\.10\.0'/);
assert.match(api,/async function register\(/);
assert.match(api,/async function stripeWebhook\(/);
assert.match(api,/subscription_status/);
assert.match(api,/Assinatura sem adimplência ativa/);
assert.match(app,/login-email/);
assert.match(app,/register-form/);
assert.match(app,/payment-action/);
assert.match(html,/Criar conta/);
assert.match(html,/Criar conta e ir para pagamento/);
assert.doesNotMatch(html,/Senha do app/);
assert.match(actionAuth,/Assinatura Veredicta sem adimplência ativa/);
assert.match(migration,/auth_user_id/);
assert.match(migration,/stripe_subscription_id/);
assert.match(migration,/subscription_status/);
console.log('v3.10 auth + billing: OK');
