import assert from 'node:assert/strict';
import fs from 'node:fs';
const api=fs.readFileSync(new URL('../api/index.js',import.meta.url),'utf8');
const auth=fs.readFileSync(new URL('../lib/actionAuth.js',import.meta.url),'utf8');
const oauth=fs.readFileSync(new URL('../lib/oauth.js',import.meta.url),'utf8');
const adminHtml=fs.readFileSync(new URL('../admin-users.html',import.meta.url),'utf8');
const adminJs=fs.readFileSync(new URL('../admin-users.js',import.meta.url),'utf8');
const openapi=fs.readFileSync(new URL('../openapi.yaml',import.meta.url),'utf8');
const migration=fs.readFileSync(new URL('../supabase/migration_v3_11_gpt_oauth.sql',import.meta.url),'utf8');
const vercel=fs.readFileSync(new URL('../vercel.json',import.meta.url),'utf8');
assert.match(api,/APP_VERSION = '3\.(?:11\.[0-9]+|1[2-9]\.[0-9]+|[2-9][0-9]\.[0-9]+)'/);
assert.match(api,/async function oauthAuthorize/);
assert.match(api,/async function oauthToken/);
assert.match(auth,/authType:'oauth'/);
assert.match(auth,/findOAuthAccessToken/);
assert.match(oauth,/refresh_token/);
assert.match(oauth,/code_challenge/);
assert.match(adminHtml,/Administração de usuários|Usuários do Veredicta/);
assert.doesNotMatch(adminHtml,/Gerar nova chave/);
assert.doesNotMatch(adminJs,/rotate_key/);
assert.match(adminJs,/revoke_gpt/);
assert.match(openapi,/type: oauth2/);
assert.match(openapi,/\/oauth\/authorize/);
assert.match(migration,/create table if not exists public\.veredicta_oauth_tokens/);
assert.match(vercel,/\/api\/oauth\/token/);
console.log('v3.11 admin + OAuth: OK');
