import assert from 'node:assert/strict';
import fs from 'node:fs';
const api=fs.readFileSync(new URL('../api/index.js',import.meta.url),'utf8');
const app=fs.readFileSync(new URL('../app.js',import.meta.url),'utf8');
const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
const css=fs.readFileSync(new URL('../styles.css',import.meta.url),'utf8');
const migration=fs.readFileSync(new URL('../supabase/migration_v3_9_multiuser.sql',import.meta.url),'utf8');
assert.match(api,/const APP_VERSION = '3\.9\.0'/);
assert.match(api,/requireUser\(req,res,json\)/);
assert.match(api,/owner_id:uid/);
assert.match(api,/synthetic=eq\.true&environment=eq\.test/);
assert.match(api,/case 'settings'/);
assert.match(html,/id="dashboard-overview"/);
assert.match(html,/id="status-donut"/);
assert.match(html,/Configurações/);
assert.match(app,/function renderDashboard/);
assert.match(app,/conic-gradient/);
assert.match(css,/--navy-950:#071a33/);
assert.match(css,/\.auth-shell/);
assert.match(migration,/owner_id uuid references auth\.users/);
assert.match(migration,/create table if not exists public\.user_settings/);
console.log('v3.9 product + multiuser architecture: OK');
