import assert from 'node:assert/strict';
import fs from 'node:fs';
const api=fs.readFileSync(new URL('../api/index.js',import.meta.url),'utf8');
const auth=fs.readFileSync(new URL('../lib/actionAuth.js',import.meta.url),'utf8');
const migration=fs.readFileSync(new URL('../supabase/migration_v3_9_multiuser.sql',import.meta.url),'utf8');
assert.match(auth,/veredicta_api_keys/);
assert.match(auth,/key_hash/);
assert.match(auth,/sha256/);
assert.match(api,/owner_id=eq\.\$\{encodeURIComponent\(principal\.userId\)\}/);
assert.match(api,/async function adminUsers/);
assert.match(api,/APP_VERSION = '3\.9\.1'/);
assert.match(api,/VALIDATOR_VERSION = '3\.8\.1'/);
assert.match(migration,/create table if not exists public\.veredicta_users/);
assert.match(migration,/create table if not exists public\.veredicta_api_keys/);
assert.match(migration,/alter table public\.cases add column if not exists owner_id/);
console.log('v3.9 multiuser regression: OK');
