import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { z } from 'zod';

const AUTH_SCHEME=[{type:'oauth2',scopes:['veredicta']}];
const READ_ONLY={readOnlyHint:true,destructiveHint:false,openWorldHint:false};
const WRITE_ANALYSIS={readOnlyHint:false,destructiveHint:false,openWorldHint:false};

const pointSchema=z.object({
  point:z.number().int().min(1).max(15),title:z.string(),legal_reference:z.string(),
  applicability:z.enum(['aplicavel','nao_aplicavel','condicional']),
  evidence_status:z.enum(['comprovado','parcialmente_comprovado','nao_comprovado','nao_consta','dispensado']),
  legal_result:z.enum(['atende','nao_atende','inconclusivo','nao_aplicavel']),
  verdict:z.string().optional(),display_label:z.string().optional(),mp_quote:z.string(),contract_quote:z.string(),reasoning:z.string()
});
const analystSchema=z.object({final_classification:z.enum(['enquadrável','parcialmente enquadrável','inconclusivo','não enquadrável']),modality:z.string().optional(),summary:z.string(),warnings:z.array(z.string()).optional(),tested_paths:z.array(z.record(z.string(),z.unknown())).optional(),points:z.array(pointSchema).length(15)});
const auditSchema=z.object({recommendation:z.enum(['liberar','corrigir','escalar para revisão humana aprofundada']),final_classification:z.enum(['enquadrável','parcialmente enquadrável','inconclusivo','não enquadrável']),findings:z.array(z.object({point:z.number().int().min(1).max(15),status:z.enum(['confirmado','divergente','não encontrado','opinião sem precedente']),reason:z.string()})).length(15),summary:z.string()});
function baseUrlFromExtra(extra){const h=extra?.requestInfo?.headers||{};const p=String(h['x-forwarded-proto']||'https').split(',')[0].trim();const host=String(h['x-forwarded-host']||h.host||'').split(',')[0].trim();return host?`${p}://${host}`.replace(/\/$/,''):String(process.env.APP_BASE_URL||'').replace(/\/$/,'')}
function bearerFromExtra(extra){if(extra?.authInfo?.token)return `Bearer ${extra.authInfo.token}`;const raw=extra?.requestInfo?.headers?.authorization;return Array.isArray(raw)?String(raw[0]||''):String(raw||'')}
function authChallenge(base,message='Entre na sua conta Veredicta para continuar.'){const metadata=`${base}/.well-known/oauth-protected-resource`;return {content:[{type:'text',text:message}],_meta:{'mcp/www_authenticate':[`Bearer resource_metadata="${metadata}", error="invalid_token", error_description="${message}"`]},isError:true}}
async function callVeredicta(extra,path,{method='GET',body}={}){const base=baseUrlFromExtra(extra),authorization=bearerFromExtra(extra);if(!base)return {content:[{type:'text',text:'APP_BASE_URL não configurado.'}],isError:true};if(!authorization)return authChallenge(base);let response;try{response=await fetch(`${base}${path}`,{method,headers:{authorization,accept:'application/json',...(body?{'content-type':'application/json'}:{})},body:body?JSON.stringify(body):undefined,signal:extra?.signal})}catch(error){return {content:[{type:'text',text:`Falha ao acessar o Veredicta: ${error.message}`}],isError:true}}const data=await response.json().catch(()=>({error:`Resposta inválida do Veredicta (${response.status})`}));if(response.status===401)return authChallenge(base,String(data?.error||'A conexão com o Veredicta expirou. Entre novamente.'));return {content:[{type:'text',text:JSON.stringify(data)}],structuredContent:{data},isError:!response.ok}}
function toolMeta(){return {securitySchemes:AUTH_SCHEME}}

export function createVeredictaMcpServer(){
 const server=new McpServer({name:'veredicta',version:'3.15.3'},{instructions:'REGRA DE BEGIN_TEST: quando o usuário disser begin_test ou /begin_test, NÃO liste a fila geral e NÃO procure lote antigo por external_test_id. Primeiro consulte status/fontes e, estando válidos, chame obrigatoriamente a ferramenta begin_test. Essa ferramenta cria ou inicia uma nova rodada cega de 100 casos no servidor. Depois use proximo_caso_treinamento_veredicta e registrar_resultado_treinamento_veredicta até success ou blocked/regression_detected. Identidade canônica é sempre case.id UUID; nunca associe por nome, título ou client_name. Para pedidos de lote/fila, prefira listar_lote_casos_veredicta. Para o Teste C use external_test_prefix VEREDICTA-REG-318- somente para selecionar o lote; depois processe exclusivamente pelos case_id UUID retornados. Revisão humana é obrigatória para casos de produção.'});
 server.registerTool('consultar_status_veredicta',{title:'Consultar status do Veredicta',description:'Retorna versões, hashes e fontes.',inputSchema:{},outputSchema:{data:z.record(z.string(),z.unknown())},annotations:READ_ONLY,_meta:toolMeta()},async(_a,e)=>callVeredicta(e,'/api/gpt/source-status'));
 server.registerTool('consultar_fontes_juridicas_veredicta',{title:'Consultar fontes jurídicas',description:'Retorna textos integrais e hashes.',inputSchema:{},outputSchema:{data:z.record(z.string(),z.unknown())},annotations:READ_ONLY,_meta:toolMeta()},async(_a,e)=>callVeredicta(e,'/api/gpt/legal-sources'));
 server.registerTool('begin_test',{title:'BEGIN TEST — gerar bateria cega de 100 casos',description:'Use obrigatoriamente quando o usuário pedir begin_test ou /begin_test. Cria uma nova execução de treinamento e 100 casos cegos no servidor. NÃO substitua por listar casos pendentes, procurar lote anterior ou reimportar arquivos.',inputSchema:{seed:z.string().min(8).max(240).optional()},outputSchema:{data:z.record(z.string(),z.unknown())},annotations:WRITE_ANALYSIS,_meta:toolMeta()},async(a,e)=>callVeredicta(e,'/api/gpt/training-start',{method:'POST',body:a||{}}));
 server.registerTool('listar_casos_veredicta',{title:'Listar casos',description:'Lista casos existentes. Não use esta ferramenta como início de begin_test; begin_test deve chamar a ferramenta begin_test.',inputSchema:{status:z.enum(['pendente','em-analise','aguardando-revisao','requer-correcao','concluido','erro']).optional(),environment:z.enum(['production','test']).optional(),run_id:z.string().uuid().optional()},outputSchema:{data:z.record(z.string(),z.unknown())},annotations:READ_ONLY,_meta:toolMeta()},async({status,environment,run_id},e)=>{const q=new URLSearchParams();if(status)q.set('status',status);if(environment)q.set('environment',environment);if(run_id)q.set('run_id',run_id);return callVeredicta(e,`/api/gpt/cases${q.toString()?`?${q}`:''}`)});
 server.registerTool('listar_lote_casos_veredicta',{title:'Listar lote completo por UUID',description:'Retorna até 100 dossiês completos de uma fila em uma única chamada. external_test_prefix serve apenas para selecionar o lote; a identidade para análise continua sendo exclusivamente case_id UUID. Para o Teste C use VEREDICTA-REG-318-.',inputSchema:{status:z.enum(['pendente','em-analise','aguardando-revisao','requer-correcao','concluido','erro']).default('pendente'),environment:z.enum(['production','test']).default('test'),limit:z.number().int().min(1).max(100).default(100),external_test_prefix:z.string().min(1).max(120).optional()},outputSchema:{data:z.record(z.string(),z.unknown())},annotations:READ_ONLY,_meta:toolMeta()},async({status,environment,limit,external_test_prefix},e)=>{const q=new URLSearchParams({status,environment,limit:String(limit)});if(external_test_prefix)q.set('external_test_prefix',external_test_prefix);return callVeredicta(e,`/api/gpt-batch-cases?${q}`)});
 server.registerTool('criar_caso_veredicta',{title:'Criar caso',description:'Cadastra caso.',inputSchema:{title:z.string().min(1).max(180),client_name:z.string().max(180).optional(),contract_text:z.string().min(1)},outputSchema:{data:z.record(z.string(),z.unknown())},annotations:WRITE_ANALYSIS,_meta:toolMeta()},async(a,e)=>callVeredicta(e,'/api/gpt/cases',{method:'POST',body:a}));
 const syntheticCase=z.object({external_test_id:z.string().regex(/^VEREDICTA-(?:TEST-\d{3,4}|REG-\d{3}-\d{3,4})$/),title:z.string().min(1),client_name:z.string().optional(),contract_text:z.string().min(1)});
 server.registerTool('importar_casos_sinteticos_veredicta',{title:'Importar casos sintéticos (legado)',description:'Importação em lote mantida por compatibilidade; prefira o fluxo fracionado.',inputSchema:{environment:z.literal('test'),batch_id:z.string().min(1).max(120),cases:z.array(syntheticCase).min(1).max(100)},outputSchema:{data:z.record(z.string(),z.unknown())},annotations:WRITE_ANALYSIS,_meta:toolMeta()},async(a,e)=>callVeredicta(e,'/api/gpt/test-import',{method:'POST',body:a}));
 server.registerTool('iniciar_importacao_lote_veredicta',{title:'Iniciar importação fracionada',description:'Abre sessão de lote com payload mínimo.',inputSchema:{environment:z.literal('test'),batch_id:z.string().min(1).max(120),expected_total:z.number().int().min(1).max(100)},outputSchema:{data:z.record(z.string(),z.unknown())},annotations:WRITE_ANALYSIS,_meta:toolMeta()},async(a,e)=>callVeredicta(e,'/api/gpt-test-import-start',{method:'POST',body:a}));
 server.registerTool('importar_caso_lote_veredicta',{title:'Importar um caso do lote',description:'Envia exatamente um caso por chamada e retorna case_id UUID.',inputSchema:{import_id:z.string().uuid(),batch_id:z.string().min(1).max(120),case:syntheticCase},outputSchema:{data:z.record(z.string(),z.unknown())},annotations:WRITE_ANALYSIS,_meta:toolMeta()},async(a,e)=>callVeredicta(e,'/api/gpt-test-import-case',{method:'POST',body:a}));
 server.registerTool('finalizar_importacao_lote_veredicta',{title:'Finalizar importação fracionada',description:'Confere IDs únicos e conclui quando expected_total foi atingido.',inputSchema:{import_id:z.string().uuid(),batch_id:z.string().min(1).max(120)},outputSchema:{data:z.record(z.string(),z.unknown())},annotations:WRITE_ANALYSIS,_meta:toolMeta()},async(a,e)=>callVeredicta(e,'/api/gpt-test-import-finalize',{method:'POST',body:a}));
 server.registerTool('iniciar_treinamento_veredicta',{title:'Iniciar treinamento cego',description:'Alias compatível para training-start. Para o comando do usuário begin_test, prefira a ferramenta begin_test.',inputSchema:{seed:z.string().min(8).max(240).optional()},outputSchema:{data:z.record(z.string(),z.unknown())},annotations:WRITE_ANALYSIS,_meta:toolMeta()},async(a,e)=>callVeredicta(e,'/api/gpt/training-start',{method:'POST',body:a||{}}));
 server.registerTool('consultar_treinamento_veredicta',{title:'Consultar treinamento',description:'Progresso agregado sem gabarito.',inputSchema:{run_id:z.string().uuid().optional()},outputSchema:{data:z.record(z.string(),z.unknown())},annotations:READ_ONLY,_meta:toolMeta()},async({run_id},e)=>callVeredicta(e,`/api/gpt/training-status${run_id?`?run_id=${encodeURIComponent(run_id)}`:''}`));
 server.registerTool('proximo_caso_treinamento_veredicta',{title:'Próximo caso cego',description:'Retorna próximo dossiê por UUID.',inputSchema:{run_id:z.string().uuid()},outputSchema:{data:z.record(z.string(),z.unknown())},annotations:READ_ONLY,_meta:toolMeta()},async({run_id},e)=>callVeredicta(e,`/api/gpt/training-next?run_id=${encodeURIComponent(run_id)}`));
 server.registerTool('registrar_resultado_treinamento_veredicta',{title:'Registrar resultado cego',description:'Compara analysis_id no servidor.',inputSchema:{run_id:z.string().uuid(),case_id:z.string().uuid(),analysis_id:z.string().uuid()},outputSchema:{data:z.record(z.string(),z.unknown())},annotations:WRITE_ANALYSIS,_meta:toolMeta()},async(a,e)=>callVeredicta(e,'/api/gpt/training-record',{method:'POST',body:a}));
 server.registerTool('buscar_caso_veredicta',{title:'Buscar caso',description:'Recupera dossiê e hash por UUID.',inputSchema:{id:z.string().uuid()},outputSchema:{data:z.record(z.string(),z.unknown())},annotations:READ_ONLY,_meta:toolMeta()},async({id},e)=>callVeredicta(e,`/api/gpt/case?id=${encodeURIComponent(id)}`));
 server.registerTool('iniciar_envio_analise_veredicta',{title:'Iniciar envio fracionado',description:'Abre rascunho.',inputSchema:{case_id:z.string().uuid(),source_contract_sha256:z.string().regex(/^[a-f0-9]{64}$/i),analyst_final_classification:z.enum(['enquadrável','parcialmente enquadrável','inconclusivo','não enquadrável']),analyst_summary:z.string(),audit_final_classification:z.enum(['enquadrável','parcialmente enquadrável','inconclusivo','não enquadrável']),audit_recommendation:z.enum(['liberar','corrigir','escalar para revisão humana aprofundada']),audit_summary:z.string()},outputSchema:{data:z.record(z.string(),z.unknown())},annotations:WRITE_ANALYSIS,_meta:toolMeta()},async(a,e)=>callVeredicta(e,'/api/gpt/analysis-start',{method:'POST',body:a}));
 server.registerTool('enviar_ponto_analise_veredicta',{title:'Enviar ponto',description:'Grava um ponto e finding.',inputSchema:{draft_id:z.string().uuid(),case_id:z.string().uuid(),analyst_point:pointSchema,audit_finding:z.object({point:z.number().int().min(1).max(15),status:z.enum(['confirmado','divergente','não encontrado','opinião sem precedente']),reason:z.string()})},outputSchema:{data:z.record(z.string(),z.unknown())},annotations:WRITE_ANALYSIS,_meta:toolMeta()},async(a,e)=>callVeredicta(e,'/api/gpt/analysis-point',{method:'POST',body:a}));
 server.registerTool('finalizar_envio_analise_veredicta',{title:'Finalizar análise',description:'Monta e valida 15 pontos.',inputSchema:{draft_id:z.string().uuid(),case_id:z.string().uuid()},outputSchema:{data:z.record(z.string(),z.unknown())},annotations:WRITE_ANALYSIS,_meta:toolMeta()},async(a,e)=>callVeredicta(e,'/api/gpt/analysis-finalize',{method:'POST',body:a}));
 server.registerTool('enviar_analise_veredicta',{title:'Enviar análise completa',description:'Compatibilidade.',inputSchema:{case_id:z.string().uuid(),source_contract_sha256:z.string().regex(/^[a-f0-9]{64}$/i),analyst:analystSchema,audit:auditSchema},outputSchema:{data:z.record(z.string(),z.unknown())},annotations:WRITE_ANALYSIS,_meta:toolMeta()},async(a,e)=>callVeredicta(e,'/api/gpt/analysis',{method:'POST',body:a}));
 server.registerTool('listar_historico_veredicta',{title:'Histórico',description:'Lista análises do caso.',inputSchema:{case_id:z.string().uuid()},outputSchema:{data:z.record(z.string(),z.unknown())},annotations:READ_ONLY,_meta:toolMeta()},async({case_id},e)=>callVeredicta(e,`/api/gpt/analysis-history?case_id=${encodeURIComponent(case_id)}`));
 server.registerTool('buscar_analise_veredicta',{title:'Detalhe da análise',description:'Busca análise por UUID.',inputSchema:{id:z.string().uuid()},outputSchema:{data:z.record(z.string(),z.unknown())},annotations:READ_ONLY,_meta:toolMeta()},async({id},e)=>callVeredicta(e,`/api/gpt/analysis-detail?id=${encodeURIComponent(id)}`));
 return server;
}