import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { z } from 'zod';

const AUTH_SCHEME=[{type:'oauth2',scopes:['veredicta']}];
const READ_ONLY={readOnlyHint:true,destructiveHint:false,openWorldHint:false};
const WRITE_ANALYSIS={readOnlyHint:false,destructiveHint:false,openWorldHint:false};

const pointSchema=z.object({
  point:z.number().int().min(1).max(15),title:z.string(),legal_reference:z.string(),
  applicability:z.enum(['aplicavel','nao_aplicavel','condicional']),
  evidence_status:z.enum(['comprovado','parcialmente_comprovado','nao_comprovado','nao_consta','dispensado']),
  legal_result:z.enum(['atende','nao_atende','inconclusivo','nao_aplicavel']),
  verdict:z.string().optional(),display_label:z.string().optional(),mp_quote:z.string(),contract_quote:z.string(),reasoning:z.string()
});
const analystSchema=z.object({final_classification:z.enum(['enquadrável','parcialmente enquadrável','inconclusivo','não enquadrável']),modality:z.string().optional(),summary:z.string(),warnings:z.array(z.string()).optional(),tested_paths:z.array(z.record(z.string(),z.unknown())).optional(),points:z.array(pointSchema).length(15)});
const auditSchema=z.object({recommendation:z.enum(['liberar','corrigir','escalar para revisão humana aprofundada']),final_classification:z.enum(['enquadrável','parcialmente enquadrável','inconclusivo','não enquadrável']),findings:z.array(z.object({point:z.number().int().min(1).max(15),status:z.enum(['confirmado','divergente','não encontrado','opinião sem precedente']),reason:z.string()})).length(15),summary:z.string()});
function baseUrlFromExtra(extra){const h=extra?.requestInfo?.headers||{};const p=String(h['x-forwarded-proto']||'https').split(',')[0].trim();const host=String(h['x-forwarded-host']||h.host||'').split(',')[0].trim();return host?`${p}://${host}`.replace(/\/$/,''):String(process.env.APP_BASE_URL||'').replace(/\/$/,'')}
function bearerFromExtra(extra){if(extra?.authInfo?.token)return `Bearer ${extra.authInfo.token}`;const raw=extra?.requestInfo?.headers?.authorization;return Array.isArray(raw)?String(raw[0]||''):String(raw||'')}
function authChallenge(base,message='Entre na sua conta Veredicta para continuar.'){const metadata=`${base}/.well-known/oauth-protected-resource`;return {content:[{type:'text',text:message}],_meta:{'mcp/www_authenticate':[`Bearer resource_metadata="${metadata}", error="invalid_token", error_description="${message}"`]},isError:true}}
function blindTrainingData(path,data){
  if(!data||typeof data!=='object')return data;
  if(path.startsWith('/api/gpt/training-start'))return {
    ok:data.ok,run_id:data.run_id,status:data.status,completed:data.completed,round_cases:data.round_cases,
    app_version:data.app_version,validator_version:data.validator_version,
    next_step:'Chame proximo_caso_treinamento_veredicta e processe os casos cegamente. O gabarito e a distribuição permanecem exclusivamente no servidor.'
  };
  if(path.startsWith('/api/gpt/training-status'))return {
    ok:data.ok,run_id:data.run_id,status:data.status,completed:data.completed,
    active_case_count:data.active_case_count,success_100_100_confirmed:data.success_100_100_confirmed,
    app_version:data.app_version,validator_version:data.validator_version
  };
  if(path.startsWith('/api/gpt/training-next'))return {
    ok:data.ok,run_id:data.run_id,case:data.case,contract_sha256:data.contract_sha256,
    app_version:data.app_version,validator_version:data.validator_version,
    legal_source_version:data.legal_source_version,memorandum_version:data.memorandum_version
  };
  if(path.startsWith('/api/gpt/training-record'))return {
    ok:data.ok,run_id:data.run_id,status:data.status,completed:data.completed,
    success_100_100_confirmed:data.success_100_100_confirmed,
    next_action:data.completed?'stop':'next_case',blocked_reason:data.blocked_reason||undefined
  };
  return data;
}
async function callVeredicta(extra,path,{method='GET',body}={}){const base=baseUrlFromExtra(extra),authorization=bearerFromExtra(extra);if(!base)return {content:[{type:'text',text:'APP_BASE_URL não configurado.'}],isError:true};if(!authorization)return authChallenge(base);let response;try{response=await fetch(`${base}${path}`,{method,headers:{authorization,accept:'application/json',...(body?{'content-type':'application/json'}:{})},body:body?JSON.stringify(body):undefined,signal:extra?.signal})}catch(error){return {content:[{type:'text',text:`Falha ao acessar o Veredicta: ${error.message}`}],isError:true}}const raw=await response.json().catch(()=>({error:`Resposta inválida do Veredicta (${response.status})`}));if(response.status===401)return authChallenge(base,String(raw?.error||'A conexão com o Veredicta expirou. Entre novamente.'));const data=blindTrainingData(path,raw);return {content:[{type:'text',text:JSON.stringify(data)}],structuredContent:{data},isError:!response.ok}}
function toolMeta(){return {securitySchemes:AUTH_SCHEME}}

export function createVeredictaMcpServer(){
 const server=new McpServer({name:'veredicta',version:'3.17.1'},{instructions:'REGRA DE EXPERIÊNCIA DO USUÁRIO — SILÊNCIO DURANTE PROCESSAMENTO: enquanto estiver executando ferramentas, lendo a petição, preparando os 15 pontos, auditando, corrigindo quality gate ou persistindo resultados, NÃO envie mensagens intermediárias ao usuário, NÃO descreva o plano, NÃO anuncie etapas e NÃO exponha diagnósticos parciais. Durante esse período, a única indicação de progresso autorizada é o rótulo da ferramenta “Analisando conforme MP...”. Só responda em linguagem natural após o fluxo terminar ou quando houver erro que exija ação do usuário. PRIORIDADE MÁXIMA — PETIÇÃO: se a mensagem atual do usuário contiver uma petição anexada ou colada e não houver ordem expressa para não cadastrar/analisar, o fluxo obrigatório é CADASTRAR + ANALISAR na mesma execução. A primeira e única ferramenta de escrita desse fluxo deve ser cadastrar_e_analisar_peticao_veredicta, já com os 15 pontos e a auditoria adversarial completos. É PROIBIDO usar criar_caso_veredicta para petição. O fluxo só termina quando a resposta retornar analysis_id/analyzed=true. Se cadastrar_e_analisar_peticao_veredicta não estiver disponível no catálogo de ferramentas, NÃO faça fallback silencioso para criar_caso_veredicta: informe que a integração está desatualizada e precisa ser recarregada. REGRA DE BEGIN_TEST: quando o usuário disser begin_test ou /begin_test, NÃO liste a fila geral e NÃO procure lote antigo por external_test_id. Primeiro consulte status/fontes e, estando válidos, chame obrigatoriamente a ferramenta begin_test. Essa ferramenta cria uma rodada cega no servidor. O agente NÃO recebe seed, distribuição, classificação esperada, pontos esperados, comparação por ponto nem indicação de acerto/erro durante a execução. Depois use proximo_caso_treinamento_veredicta e registrar_resultado_treinamento_veredicta até success ou blocked/regression_detected. Identidade canônica é sempre case.id UUID; nunca associe por nome, título ou client_name. Para pedidos de lote/fila, prefira listar_lote_casos_veredicta. Para o Teste C use external_test_prefix VEREDICTA-REG-318- somente para selecionar o lote; depois processe exclusivamente pelos case_id UUID retornados. Revisão humana é obrigatória para casos de produção. REGRA DE PETIÇÃO: quando o usuário enviar ou anexar uma petição, salvo ordem expressa em contrário, leia o documento integralmente, execute os 15 pontos e a auditoria adversarial e use cadastrar_e_analisar_peticao_veredicta. Não peça cadastro manual, não crie o caso separadamente e não use resumo no lugar do texto integral da petição.'});
 server.registerTool('consultar_status_veredicta',{title:'Consultar status do Veredicta',description:'Retorna versões, hashes e fontes.',inputSchema:{},outputSchema:{data:z.record(z.string(),z.unknown())},annotations:READ_ONLY,_meta:toolMeta()},async(_a,e)=>callVeredicta(e,'/api/gpt/source-status'));
 server.registerTool('consultar_fontes_juridicas_veredicta',{title:'Consultar fontes jurídicas',description:'Retorna textos integrais e hashes.',inputSchema:{},outputSchema:{data:z.record(z.string(),z.unknown())},annotations:READ_ONLY,_meta:toolMeta()},async(_a,e)=>callVeredicta(e,'/api/gpt/legal-sources'));
 server.registerTool('begin_test',{title:'BEGIN TEST — gerar bateria cega de 100 casos',description:'Use obrigatoriamente quando o usuário pedir begin_test ou /begin_test. Cria nova execução cega; o gabarito permanece exclusivamente server-side.',inputSchema:{seed:z.string().min(8).max(240).optional()},outputSchema:{data:z.record(z.string(),z.unknown())},annotations:WRITE_ANALYSIS,_meta:toolMeta()},async(a,e)=>callVeredicta(e,'/api/gpt/training-start',{method:'POST',body:a||{}}));
 server.registerTool('listar_casos_veredicta',{title:'Listar casos',description:'Lista casos existentes. Não use esta ferramenta como início de begin_test; begin_test deve chamar a ferramenta begin_test.',inputSchema:{status:z.enum(['pendente','em-analise','aguardando-revisao','requer-correcao','concluido','erro']).optional(),environment:z.enum(['production','test']).optional(),run_id:z.string().uuid().optional()},outputSchema:{data:z.record(z.string(),z.unknown())},annotations:READ_ONLY,_meta:toolMeta()},async({status,environment,run_id},e)=>{const q=new URLSearchParams();if(status)q.set('status',status);if(environment)q.set('environment',environment);if(run_id)q.set('run_id',run_id);return callVeredicta(e,`/api/gpt/cases${q.toString()?`?${q}`:''}`)});
 server.registerTool('listar_lote_casos_veredicta',{title:'Listar lote completo por UUID',description:'Retorna até 100 dossiês completos de uma fila em uma única chamada. external_test_prefix serve apenas para selecionar o lote; a identidade para análise continua sendo exclusivamente case_id UUID. Para o Teste C use VEREDICTA-REG-318-.',inputSchema:{status:z.enum(['pendente','em-analise','aguardando-revisao','requer-correcao','concluido','erro']).default('pendente'),environment:z.enum(['production','test']).default('test'),limit:z.number().int().min(1).max(100).default(100),external_test_prefix:z.string().min(1).max(120).optional()},outputSchema:{data:z.record(z.string(),z.unknown())},annotations:READ_ONLY,_meta:toolMeta()},async({status,environment,limit,external_test_prefix},e)=>{const q=new URLSearchParams({status,environment,limit:String(limit)});if(external_test_prefix)q.set('external_test_prefix',external_test_prefix);return callVeredicta(e,`/api/gpt-batch-cases?${q}`)});
 server.registerTool('criar_caso_veredicta',{title:'Criar caso',description:'Cadastra caso para contratos ou outros documentos. NÃO use esta ferramenta quando a entrada for uma petição; nesse caso use obrigatoriamente cadastrar_e_analisar_peticao_veredicta para cadastrar e analisar no mesmo fluxo.',inputSchema:{title:z.string().min(1).max(180),client_name:z.string().max(180).optional(),contract_text:z.string().min(1)},outputSchema:{data:z.record(z.string(),z.unknown())},annotations:WRITE_ANALYSIS,_meta:toolMeta()},async(a,e)=>callVeredicta(e,'/api/gpt/cases',{method:'POST',body:a}));
 server.registerTool('cadastrar_e_analisar_peticao_veredicta',{title:'Analisando conforme MP...',description:'FERRAMENTA OBRIGATÓRIA PARA PETIÇÕES REAIS. Execute silenciosamente até o resultado final; não gere mensagens intermediárias ao usuário. Em uma única escrita, cadastra o texto integral da petição como caso de produção e grava imediatamente a análise completa dos 15 pontos com auditoria adversarial. Não use criar_caso_veredicta antes desta ferramenta. O fluxo só é considerado concluído quando houver analysis_id e analyzed=true.',inputSchema:{title:z.string().min(1).max(180),client_name:z.string().max(180).optional(),petition_text:z.string().min(1),analyst:analystSchema,audit:auditSchema},outputSchema:{data:z.record(z.string(),z.unknown())},annotations:WRITE_ANALYSIS,_meta:toolMeta()},async(a,e)=>callVeredicta(e,'/api/gpt/petition-analyze',{method:'POST',body:a}));
 const syntheticCase=z.object({external_test_id:z.string().regex(/^VEREDICTA-(?:TEST-\d{3,4}|REG-\d{3}-\d{3,4})$/),title:z.string().min(1),client_name:z.string().optional(),contract_text:z.string().min(1)});
 server.registerTool('importar_casos_sinteticos_veredicta',{title:'Importar casos sintéticos (legado)',description:'Importação em lote mantida por compatibilidade; prefira o fluxo fracionado.',inputSchema:{environment:z.literal('test'),batch_id:z.string().min(1).max(120),cases:z.array(syntheticCase).min(1).max(100)},outputSchema:{data:z.record(z.string(),z.unknown())},annotations:WRITE_ANALYSIS,_meta:toolMeta()},async(a,e)=>callVeredicta(e,'/api/gpt/test-import',{method:'POST',body:a}));
 server.registerTool('iniciar_importacao_lote_veredicta',{title:'Iniciar importação fracionada',description:'Abre sessão de lote com payload mínimo.',inputSchema:{environment:z.literal('test'),batch_id:z.string().min(1).max(120),expected_total:z.number().int().min(1).max(100)},outputSchema:{data:z.record(z.string(),z.unknown())},annotations:WRITE_ANALYSIS,_meta:toolMeta()},async(a,e)=>callVeredicta(e,'/api/gpt-test-import-start',{method:'POST',body:a}));
 server.registerTool('importar_caso_lote_veredicta',{title:'Importar um caso do lote',description:'Envia exatamente um caso por chamada e retorna case_id UUID.',inputSchema:{import_id:z.string().uuid(),batch_id:z.string().min(1).max(120),case:syntheticCase},outputSchema:{data:z.record(z.string(),z.unknown())},annotations:WRITE_ANALYSIS,_meta:toolMeta()},async(a,e)=>callVeredicta(e,'/api/gpt-test-import-case',{method:'POST',body:a}));
 server.registerTool('finalizar_importacao_lote_veredicta',{title:'Finalizar importação fracionada',description:'Confere IDs únicos e conclui quando expected_total foi atingido.',inputSchema:{import_id:z.string().uuid(),batch_id:z.string().min(1).max(120)},outputSchema:{data:z.record(z.string(),z.unknown())},annotations:WRITE_ANALYSIS,_meta:toolMeta()},async(a,e)=>callVeredicta(e,'/api/gpt-test-import-finalize',{method:'POST',body:a}));
 server.registerTool('iniciar_treinamento_veredicta',{title:'Iniciar treinamento cego',description:'Alias compatível para training-start. O gabarito permanece server-side.',inputSchema:{seed:z.string().min(8).max(240).optional()},outputSchema:{data:z.record(z.string(),z.unknown())},annotations:WRITE_ANALYSIS,_meta:toolMeta()},async(a,e)=>callVeredicta(e,'/api/gpt/training-start',{method:'POST',body:a||{}}));
 server.registerTool('consultar_treinamento_veredicta',{title:'Consultar treinamento',description:'Retorna somente progresso público sem gabarito, distribuição ou feedback de correção.',inputSchema:{run_id:z.string().uuid().optional()},outputSchema:{data:z.record(z.string(),z.unknown())},annotations:READ_ONLY,_meta:toolMeta()},async({run_id},e)=>callVeredicta(e,`/api/gpt/training-status${run_id?`?run_id=${encodeURIComponent(run_id)}`:''}`));
 server.registerTool('proximo_caso_treinamento_veredicta',{title:'Próximo caso cego',description:'Retorna apenas o próximo dossiê por UUID e seu hash; não retorna progresso classificatório.',inputSchema:{run_id:z.string().uuid()},outputSchema:{data:z.record(z.string(),z.unknown())},annotations:READ_ONLY,_meta:toolMeta()},async({run_id},e)=>callVeredicta(e,`/api/gpt/training-next?run_id=${encodeURIComponent(run_id)}`));
 server.registerTool('registrar_resultado_treinamento_veredicta',{title:'Registrar resultado cego',description:'Compara analysis_id no servidor sem revelar se o caso acertou, qual era o esperado ou quais pontos divergiram.',inputSchema:{run_id:z.string().uuid(),case_id:z.string().uuid(),analysis_id:z.string().uuid()},outputSchema:{data:z.record(z.string(),z.unknown())},annotations:WRITE_ANALYSIS,_meta:toolMeta()},async(a,e)=>callVeredicta(e,'/api/gpt/training-record',{method:'POST',body:a}));
 server.registerTool('buscar_caso_veredicta',{title:'Buscar caso',description:'Recupera dossiê e hash por UUID.',inputSchema:{id:z.string().uuid()},outputSchema:{data:z.record(z.string(),z.unknown())},annotations:READ_ONLY,_meta:toolMeta()},async({id},e)=>callVeredicta(e,`/api/gpt/case?id=${encodeURIComponent(id)}`));
 server.registerTool('iniciar_envio_analise_veredicta',{title:'Iniciar envio fracionado',description:'Fallback para payload grande ou falha de transporte. Para menor latência, prefira enviar_analise_veredicta em uma única chamada.',inputSchema:{case_id:z.string().uuid(),source_contract_sha256:z.string().regex(/^[a-f0-9]{64}$/i),analyst_final_classification:z.enum(['enquadrável','parcialmente enquadrável','inconclusivo','não enquadrável']),analyst_summary:z.string(),audit_final_classification:z.enum(['enquadrável','parcialmente enquadrável','inconclusivo','não enquadrável']),audit_recommendation:z.enum(['liberar','corrigir','escalar para revisão humana aprofundada']),audit_summary:z.string()},outputSchema:{data:z.record(z.string(),z.unknown())},annotations:WRITE_ANALYSIS,_meta:toolMeta()},async(a,e)=>callVeredicta(e,'/api/gpt/analysis-start',{method:'POST',body:a}));
 server.registerTool('enviar_ponto_analise_veredicta',{title:'Enviar ponto',description:'Grava um ponto e finding. Use somente no fallback fracionado; o fluxo rápido envia os 15 pontos em uma chamada.',inputSchema:{draft_id:z.string().uuid(),case_id:z.string().uuid(),analyst_point:pointSchema,audit_finding:z.object({point:z.number().int().min(1).max(15),status:z.enum(['confirmado','divergente','não encontrado','opinião sem precedente']),reason:z.string()})},outputSchema:{data:z.record(z.string(),z.unknown())},annotations:WRITE_ANALYSIS,_meta:toolMeta()},async(a,e)=>callVeredicta(e,'/api/gpt/analysis-point',{method:'POST',body:a}));
 server.registerTool('finalizar_envio_analise_veredicta',{title:'Finalizar análise',description:'Finaliza o fallback fracionado e executa o mesmo quality gate do envio completo.',inputSchema:{draft_id:z.string().uuid(),case_id:z.string().uuid()},outputSchema:{data:z.record(z.string(),z.unknown())},annotations:WRITE_ANALYSIS,_meta:toolMeta()},async(a,e)=>callVeredicta(e,'/api/gpt/analysis-finalize',{method:'POST',body:a}));
 server.registerTool('enviar_analise_veredicta',{title:'Enviar análise completa',description:'Fluxo rápido preferencial: envia analista + auditoria em uma única chamada e executa hash, validação, quality gate e persistência sem reduzir a qualidade.',inputSchema:{case_id:z.string().uuid(),source_contract_sha256:z.string().regex(/^[a-f0-9]{64}$/i),analyst:analystSchema,audit:auditSchema},outputSchema:{data:z.record(z.string(),z.unknown())},annotations:WRITE_ANALYSIS,_meta:toolMeta()},async(a,e)=>callVeredicta(e,'/api/gpt/analysis',{method:'POST',body:a}));
 server.registerTool('listar_historico_veredicta',{title:'Histórico',description:'Lista análises do caso.',inputSchema:{case_id:z.string().uuid()},outputSchema:{data:z.record(z.string(),z.unknown())},annotations:READ_ONLY,_meta:toolMeta()},async({case_id},e)=>callVeredicta(e,`/api/gpt/analysis-history?case_id=${encodeURIComponent(case_id)}`));
 server.registerTool('buscar_analise_veredicta',{title:'Detalhe da análise',description:'Busca análise por UUID.',inputSchema:{id:z.string().uuid()},outputSchema:{data:z.record(z.string(),z.unknown())},annotations:READ_ONLY,_meta:toolMeta()},async({id},e)=>callVeredicta(e,`/api/gpt/analysis-detail?id=${encodeURIComponent(id)}`));
 return server;
}
